# Build Stage
FROM gradle:7-jdk11 AS builder

COPY --chown=gradle:gradle . /home/gradle/src

WORKDIR /home/gradle/src

RUN gradle build --no-daemon

# Run Stage
FROM openjdk:11-jre-slim

EXPOSE 8081

RUN mkdir /app

COPY --from=builder /home/gradle/src/build/libs/*.jar /app/

ENTRYPOINT ["java", "-jar", "/app/users-0.0.1-SNAPSHOT.jar"]